import './index.css'
export { default as AddressInput } from './components/inputs/AddressInput.vue'
export { default as CepInput } from './components/inputs/CepInput.vue'
export { default as CityInput } from './components/inputs/CityInput.vue'
export { default as CpfCnpjInput } from './components/inputs/CpfCnpjInput.vue'
export { default as EmailInput } from './components/inputs/EmailInput.vue'
export { default as NameInput } from './components/inputs/NameInput.vue'
export { default as NumberAddressInput } from './components/inputs/NumberAddressInput.vue'
export { default as PasswordInput } from './components/inputs/PasswordInput.vue'
export { default as PhoneNumberInput } from './components/inputs/PhoneNumberInput.vue'
export { default as SearchBoxInput } from './components/inputs/SearchBoxInput.vue'
export { default as StateInput } from './components/inputs/StateInput.vue'
